config/routes.rb
Pidabluray::Application.routes.draw do
  resources :categorizations

  resources :categories

  get "store/index"

  resources :products

    root :to => 'store#index', :as => 'store'

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
  
  attr_accessible :category_id, :created_at, :position, :product_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :products, :through => :categorizations
  
  attr_accessible :name
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :categorizations
  has_many :categories, :through => :categorizations
  
  default_scope :order => 'id'
  attr_accessible :description, :id, :image_url, :price, :title, :trailer, :released_at, :evaluation, :category_ids, :name
  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  
# 
  validates :image_url, :format => {
    :with    => %r{\.(gif|jpg|png)$}i,
    :message => 'must be a URL for GIF, JPG or PNG image.'
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/categorizations_controller.rb
class CategorizationsController < ApplicationController
  # GET /categorizations
  # GET /categorizations.json
  def index
    @categorizations = Categorization.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categorizations }
    end
  end

  # GET /categorizations/1
  # GET /categorizations/1.json
  def show
    @categorization = Categorization.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @categorization }
    end
  end

  # GET /categorizations/new
  # GET /categorizations/new.json
  def new
    @categorization = Categorization.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @categorization }
    end
  end

  # GET /categorizations/1/edit
  def edit
    @categorization = Categorization.find(params[:id])
  end

  # POST /categorizations
  # POST /categorizations.json
  def create
    @categorization = Categorization.new(params[:categorization])

    respond_to do |format|
      if @categorization.save
        format.html { redirect_to @categorization, notice: 'Categorization was successfully created.' }
        format.json { render json: @categorization, status: :created, location: @categorization }
      else
        format.html { render action: "new" }
        format.json { render json: @categorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categorizations/1
  # PUT /categorizations/1.json
  def update
    @categorization = Categorization.find(params[:id])

    respond_to do |format|
      if @categorization.update_attributes(params[:categorization])
        format.html { redirect_to @categorization, notice: 'Categorization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @categorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorizations/1
  # DELETE /categorizations/1.json
  def destroy
    @categorization = Categorization.find(params[:id])
    @categorization.destroy

    respond_to do |format|
      format.html { redirect_to categorizations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.order("id").page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new

    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
  
    @product = Product.find(params[:id])
  
  end

  # POST /products
  # POST /products.json
  def create
    
    if params[:product][:category_ids]
      params[:product][:category_ids] = params[:product][:category_ids].map{|k, v| k}
    else
      params[:product][:category_ids] = []
    end
  
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update

    if params[:product][:category_ids]
      params[:product][:category_ids] = params[:product][:category_ids].map{|k, v| k}
    else
      params[:product][:category_ids] = []
    end

    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order("id").page(params[:page]).per(5)
    
    @date = Date.today.strftime("%m-%d-%Y")
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categorizations_helper.rb
module CategorizationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categorizations/_form.html.erb
<%= form_for(@categorization) do |f| %>
  <% if @categorization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categorization.errors.count, "error") %> prohibited this categorization from being saved:</h2>

      <ul>
      <% @categorization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categorizations/edit.html.erb
<h1>Editing categorization</h1>

<%= render 'form' %>

<%= link_to 'Show', @categorization %> |
<%= link_to 'Back', categorizations_path %>

app/views/categorizations/index.html.erb
<h1>Listing categorizations</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Category</th>
    <th>Position</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categorizations.each do |categorization| %>
  <tr>
    <td><%= categorization.product_id %></td>
    <td><%= categorization.category_id %></td>
    <td><%= categorization.position %></td>
    <td><%= categorization.created_at %></td>
    <td><%= link_to 'Show', categorization %></td>
    <td><%= link_to 'Edit', edit_categorization_path(categorization) %></td>
    <td><%= link_to 'Destroy', categorization, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Categorization', new_categorization_path %>

app/views/categorizations/new.html.erb
<h1>New categorization</h1>

<%= render 'form' %>

<%= link_to 'Back', categorizations_path %>

app/views/categorizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @categorization.product_id %>
</p>

<p>
  <b>Category:</b>
  <%= @categorization.category_id %>
</p>

<p>
  <b>Position:</b>
  <%= @categorization.position %>
</p>

<p>
  <b>Created at:</b>
  <%= @categorization.created_at %>
</p>


<%= link_to 'Edit', edit_categorization_path(@categorization) %> |
<%= link_to 'Back', categorizations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pidabluray</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>  
  
  </head>
<body id="store" >
  <div id="banner" >
    <%= image_tag("logo.jpg") %>
    <%= @page_title || "Peliculas Bluray" %>
  </div>
    <div id="columns" >
    <div id="side" >
      <a ><%= @date %></a><br />
      
      <a <%= link_to "Inicio", store_index_path %></a><br />
      
    </div>
    <div id="main" >

      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 10 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :evaluation %><br />
    <%= f.text_field :evaluation %>
  </div>
  <div class="field">
    <%= f.label :trailer %><br />
    <%= f.text_field :trailer %>
  </div>
  
  <div class="field">
    <%= f.label :released_at %><br />
    <%= f.text_field :released_at %>
  </div>
  
  <div class="field">
    <%= label_tag 'categories' %><br />
    <% for category in Category.all do  %>
      <%= check_box_tag "product[category_ids][#{category.id}]", nil, @product.categories.member?(category) %><%= category.name %>
    <% end %>
  </div>  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>


<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="product_list" >
  <h1>Listing products</h1>
  
  <table>
  
  <%= paginate @products %>
  
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>" >
      
      <td>
        <%= image_tag(product.image_url, :class => 'list_image') %>
      </td>
      
      <td class="list_description" >
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description),
                  :length => 80) %></dd>
          <dt><%= product.id %></dt>  
          <dt><%= product.evaluation %></dt>  
          </dl>
        </td>
        <p>

        <td class="list_actions" >
          <%= link_to 'Show', product %><br/>
          <%= link_to 'Edit', edit_product_path(product) %><br/>
          <%= link_to 'Destroy', product,
              :confirm => 'Are you sure?',
              :method => :delete %>
        </td>
      </tr>
    <% end %>
    </table>
  </div>

<br />

<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @product.id %>
</p>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Associated categories:</b>
  <%= @product.categories.map{|p| p.name}.to_sentence %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<% if notice %>
<p id="notice" ><%= notice %></p>
<% end %>

<h1>Catálogo</h1>
  
<%= paginate @products %>

<% @products.each do |product| %>
  <div class="entry" >
  <%= image_tag(product.image_url) %>
  <h3><%= product.title %></h3>
  <%=sanitize product.description %>
  <div class="price_line" >
    <span class="price" ><%= number_to_currency(product.price) %></span>
  </div>
  <div class="id_line" >
    <span><%= "ID:" %></span>
    <span class="id"><%= product.id %></span>
  </div>
  
  <div class="trailer_line" >
    <a href="<%= product.trailer %>" >Ver Trailer</a><br />
  </div>    
  <div class="released_at_line" >
    <span class="released_at:"> en nuestro catalogo desde: <%= product.released_at %></span>
  </div>
 
  <div class="evaluation_line" >
    <span class="evaluation:"><%= product.evaluation %></span>
  </div>
    
</div>
<% end %>